input GenerateLink {
  email: String!
  title: String
}

type Response {
  success: Boolean!
  message: String
}
type Report {
  title: String
  createdAt: String
}

type Query {
  report(uid: String): Report
}

type Mutation {
  generateLink(data: GenerateLink!): Response
}
