input GenerateLink {
  email: String!
    @stringLength(min: 0, max: 200)
    @pattern(
      regexp: "^(([^<>()[\\]\\\\.,;:\\s@\"]+(\\.[^<>()[\\]\\\\.,;:\\s@\"]+)*)|(\".+\"))@((\\[[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\])|(([a-zA-Z\\-0-9]+\\.)+[a-zA-Z]{2,}))$"
      flags: "i"
    )
  title: String @stringLength(min: 0, max: 200)
}

type Response {
  success: Boolean!
  message: String
}
type Report {
  title: String
  createdAt: String
}

type Query {
  report(uid: String): Report
}

type Mutation {
  generateLink(data: GenerateLink!): Response
}
